/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author b-hou
 */
public class SalesSystem extends javax.swing.JFrame {

    /**
     * Creates new form SalesSystem
     */
    public SalesSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblTax2 = new javax.swing.JLabel();
        jlblSubTotal2 = new javax.swing.JLabel();
        jlblTotal2 = new javax.swing.JLabel();
        jtxtFiletOFish = new javax.swing.JTextField();
        jtxtChickenBurger = new javax.swing.JTextField();
        jtxtChickenLegend = new javax.swing.JTextField();
        jlblSubTotal4 = new javax.swing.JLabel();
        jtxtBaconCheeseBurger = new javax.swing.JTextField();
        jtxtChickenM = new javax.swing.JTextField();
        jlblTax4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlblSubTotal5 = new javax.swing.JLabel();
        jtxtCostOfDrinks = new javax.swing.JTextField();
        jtxtCostOfMeal = new javax.swing.JTextField();
        jlblTax5 = new javax.swing.JLabel();
        jlblSubTotal6 = new javax.swing.JLabel();
        jtxtCostOfItems = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jlblTax1 = new javax.swing.JLabel();
        jlblSubTotal1 = new javax.swing.JLabel();
        jlblTotal1 = new javax.swing.JLabel();
        jtxtMilkshake = new javax.swing.JTextField();
        jtxtVanillaCone = new javax.swing.JTextField();
        jtxtClassicVanilla = new javax.swing.JTextField();
        jlblSubTotal3 = new javax.swing.JLabel();
        jtxtChocMilkShake = new javax.swing.JTextField();
        jtxtVanillaMilkShake = new javax.swing.JTextField();
        jlblTax3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurant System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jlblTax2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax2.setText("Fillet-O-Fish");

        jlblSubTotal2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal2.setText("Chicken Burger");

        jlblTotal2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTotal2.setText("Chicken Legend");

        jtxtFiletOFish.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtFiletOFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtChickenLegend.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtChickenLegend.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblSubTotal4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal4.setText("Bacon and Cheese Burger");

        jtxtBaconCheeseBurger.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtBaconCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtChickenM.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtChickenM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenMActionPerformed(evt);
            }
        });

        jlblTax4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax4.setText("Chicken Burger Meal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtChickenM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jtxtChickenBurger))
                            .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal2))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax4))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal4))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jlblSubTotal5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal5.setText("Cost of drinks");

        jtxtCostOfDrinks.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtCostOfDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtCostOfMeal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtCostOfMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTax5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax5.setText("Cost of meal");

        jlblSubTotal6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal6.setText("Total Cost of Made");

        jtxtCostOfItems.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtCostOfItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTax5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSubTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtCostOfMeal)
                            .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCostOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal5)
                    .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal6)
                    .addComponent(jtxtCostOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jlblTax1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblTax1.setText("Milkshake");

        jlblSubTotal1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblSubTotal1.setText("Vanilla Cone");

        jlblTotal1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTotal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblTotal1.setText("Classic Vanilla");

        jtxtMilkshake.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtMilkshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtVanillaCone.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtVanillaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtClassicVanilla.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtClassicVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblSubTotal3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblSubTotal3.setText("Chocolate Milkshake");

        jtxtChocMilkShake.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtChocMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtVanillaMilkShake.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtVanillaMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTax3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblTax3.setText("Vinalla Milk Shake");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTax3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblTax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jlblSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jtxtVanillaMilkShake, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtMilkshake)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax1)
                    .addComponent(jtxtMilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal1)
                    .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVanillaMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax3))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal3)
                    .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTax.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTax.setText("tax");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlblTotal.setText("Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jtxtTotal))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 12));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtChickenMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenMActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField cleartext = null;
        for (Component c : jPanel4.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("0");
            }
        }
        for (Component c : jPanel5.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("0");
            }
        }
        for (Component c : jPanel6.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        for (Component c : jPanel2.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("0");
            }
        }
        for (Component c : jPanel3.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        SubClass_Child ItemCost = new SubClass_Child();
        double iTax, iSubTotal, iTotal;
        ItemCost.Filet_O_Fish = ItemCost.pFilet_O_Fish * Double.parseDouble(jtxtFiletOFish.getText());
        ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        ItemCost.ChickenLegend = ItemCost.pChickenLegend * Double.parseDouble(jtxtChickenLegend.getText());
        ItemCost.ChickenBurgerM = ItemCost.pChickenBurgerM * Double.parseDouble(jtxtChickenM.getText());
        ItemCost.BaconCheeseBurger = ItemCost.pBaconCheeseBurger * Double.parseDouble(jtxtBaconCheeseBurger.getText());

        ItemCost.MilkShake = ItemCost.pMilkShake * Double.parseDouble(jtxtMilkshake.getText());
        ItemCost.VanillaCone = ItemCost.pVanillaCone * Double.parseDouble(jtxtVanillaCone.getText());
        ItemCost.ClasVanilla = ItemCost.pClasVanilla * Double.parseDouble(jtxtClassicVanilla.getText());
        ItemCost.VanMilkShake = ItemCost.pVanMilkShake * Double.parseDouble(jtxtVanillaMilkShake.getText());
        ItemCost.ChocMilkShake = ItemCost.pChocMilkShake * Double.parseDouble(jtxtChocMilkShake.getText());

        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;

        String SubTotal = String.format("£%.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);

        String Tax = String.format("£%.2f", iTax);
        jtxtTax.setText(Tax);

        String Total = String.format("£%.2f", iTotal);
        jtxtTotal.setText(Total);

        String Meal = String.format("£%.2f", ItemCost.Meals);
        jtxtCostOfMeal.setText(Meal);

        String Drink = String.format("£%.2f", ItemCost.Drinks);
        jtxtCostOfDrinks.setText(Drink);

        String TotalCost = String.format("£%.2f", ItemCost.TotalofMD);
        jtxtCostOfItems.setText(TotalCost);

    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        int refs = 1325 + (int) (Math.random() * 4238);

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yy");
        Tdate.format(timer.getTime());

        jtxtReceipt.append("Restaurant Management Systems\n" + "Reference:" + refs + "\n===================================\n" + "Meals:\t\t" + jtxtCostOfMeal.getText()
                + "\n\n" + "Drinks:\t\t" + jtxtCostOfDrinks.getText() + "\n\n" + "Cost of items:\t" + jtxtCostOfItems.getText() + "\n\n" + "============================="
                + "\n\n" + "Tax:\t\t" + jtxtTax.getText() + "\n\n" + "Subtotal:\t" + jtxtSubTotal.getText() + "\n\n" + "Total:\t\t" + jtxtTotal.getText() + "\n" + 
                "================================" + 
                "\nDate: " + Tdate.format(timer.getTime()) + "\tTime: " + tTime.format(timer.getTime()) + "\n\n\t\tThank you ");
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal1;
    private javax.swing.JLabel jlblSubTotal2;
    private javax.swing.JLabel jlblSubTotal3;
    private javax.swing.JLabel jlblSubTotal4;
    private javax.swing.JLabel jlblSubTotal5;
    private javax.swing.JLabel jlblSubTotal6;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax1;
    private javax.swing.JLabel jlblTax2;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTax5;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal1;
    private javax.swing.JLabel jlblTotal2;
    private javax.swing.JTextField jtxtBaconCheeseBurger;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenLegend;
    private javax.swing.JTextField jtxtChickenM;
    private javax.swing.JTextField jtxtChocMilkShake;
    private javax.swing.JTextField jtxtClassicVanilla;
    private javax.swing.JTextField jtxtCostOfDrinks;
    private javax.swing.JTextField jtxtCostOfItems;
    private javax.swing.JTextField jtxtCostOfMeal;
    private javax.swing.JTextField jtxtFiletOFish;
    private javax.swing.JTextField jtxtMilkshake;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVanillaCone;
    private javax.swing.JTextField jtxtVanillaMilkShake;
    // End of variables declaration//GEN-END:variables
}
